// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXMoVi60bM2amXUy5ubK8XCFJ83Hc0mcc',
    appId: '1:324371651091:web:f8af029e7685c1b783fde6',
    messagingSenderId: '324371651091',
    projectId: 'collaborator-app-f035c',
    authDomain: 'collaborator-app-f035c.firebaseapp.com',
    storageBucket: 'collaborator-app-f035c.appspot.com',
    measurementId: 'G-50S98XP02D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDB7EsGoejoyJf8CRfDIbx4ueDpw69sAg',
    appId: '1:324371651091:android:9ed969f53785de8083fde6',
    messagingSenderId: '324371651091',
    projectId: 'collaborator-app-f035c',
    storageBucket: 'collaborator-app-f035c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1PHtmCPpz7_uK_O3iHPKB-gfmTc92Urk',
    appId: '1:324371651091:ios:8392340441a901e183fde6',
    messagingSenderId: '324371651091',
    projectId: 'collaborator-app-f035c',
    storageBucket: 'collaborator-app-f035c.appspot.com',
    iosClientId: '324371651091-8a8g57f1f60lgcdd47e18o41n1e9fvee.apps.googleusercontent.com',
    iosBundleId: 'com.example.collaboratorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1PHtmCPpz7_uK_O3iHPKB-gfmTc92Urk',
    appId: '1:324371651091:ios:8392340441a901e183fde6',
    messagingSenderId: '324371651091',
    projectId: 'collaborator-app-f035c',
    storageBucket: 'collaborator-app-f035c.appspot.com',
    iosClientId: '324371651091-8a8g57f1f60lgcdd47e18o41n1e9fvee.apps.googleusercontent.com',
    iosBundleId: 'com.example.collaboratorApp',
  );
}
